[project]
name = "torch_dpmm"
version = "0.0.5"
authors = [
  { name="Daniele Castellana", email="danielecastellana22@gmail.com" },
]
description = "A torch implementation of DPMM"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'torch',
    'numpy',
    'scipy',
    'scikit-learn',
]

[project.urls]
Homepage = "https://github.com/danielecastellana22/torch_dp"
